import unittest
from urllib.parse import urlencode

from scripts.kgr_title_supply import (
    COUNT_METHOD,
    METHOD_VERSION,
    QUERY_SYNTAX,
    TOKENIZER_VERSION,
    build_strict_query,
    canonicalize_result_url,
    evaluate_observation,
)


def organic(keyword, suffix, title=None, **overrides):
    item = {
        "organic": True,
        "result_type": "organic",
        "canonical_url": f"https://example.com/{suffix}",
        "displayed_title": title or f"Best {keyword} online",
    }
    item.update(overrides)
    return item


def page(number, results, exhausted=False, keyword="context tool", **overrides):
    query = build_strict_query(keyword)
    parameters = {
        "q": query,
        "hl": "en",
        "gl": "us",
        "pws": "0",
        "filter": "0",
        "nfpr": "1",
        "start": str((number - 1) * 10),
    }
    value = {
        "page_url": f"https://www.google.com/search?{urlencode(parameters)}",
        "results": results,
        "exhausted": exhausted,
        "captcha": False,
        "blocked": False,
        "has_next_control": not exhausted,
        "_autogenerated_page_url": "page_url" not in overrides,
    }
    if exhausted:
        value.update(
            {
                "pagination_state": "end_of_results",
                "end_of_results_evidence": "next_control_absent_after_terminal_page",
                "has_next_control": False,
            }
        )
    value.update(overrides)
    return value


def observation(keyword, volume, pages, **overrides):
    payload = {
        "keyword": keyword,
        "volume": volume,
        "query": build_strict_query(keyword),
        "method_version": METHOD_VERSION,
        "query_syntax": QUERY_SYNTAX,
        "tokenizer_version": TOKENIZER_VERSION,
        "count_method": COUNT_METHOD,
        "page_size": 10,
        "query_context": {
            "hl": "en",
            "gl": "us",
            "device": "desktop",
            "search_type": "google_web",
            "pws": 0,
            "filter": 0,
            "nfpr": 1,
            "checked_date": "2026-08-14",
        },
        "pages": pages,
    }
    for index, current_page in enumerate(payload["pages"], start=1):
        if current_page.pop("_autogenerated_page_url", False):
            current_page["page_url"] = page(
                index,
                [],
                exhausted=current_page.get("exhausted") is True,
                keyword=keyword,
            )["page_url"]
    payload.update(overrides)
    return payload


class StrictTitleSupplyTest(unittest.TestCase):
    def test_builds_strict_per_token_query(self):
        self.assertEqual(
            build_strict_query("graph maker with x and y values"),
            'intitle:"graph" intitle:"maker" intitle:"with" intitle:"x" intitle:"and" intitle:"y" intitle:"values"',
        )

    def test_quotes_ampersand_compounds_and_preserves_stopwords_non_ascii(self):
        self.assertEqual(
            build_strict_query("Ｐ＆Ｌ maker for café"),
            'intitle:"P&L" intitle:"maker" intitle:"for" intitle:"café"',
        )
        self.assertEqual(
            build_strict_query("r&b b&w p&id"),
            'intitle:"r&b" intitle:"b&w" intitle:"p&id"',
        )
        self.assertEqual(
            build_strict_query("c++ c# maker & converter"),
            'intitle:"c++" intitle:"c#" intitle:"maker" intitle:"converter"',
        )

    def test_url_dedup_removes_display_tracking_but_preserves_business_parameters(self):
        left = canonicalize_result_url(
            "https://Example.com/tool?id=7&utm_source=google&gclid=abc&fbclid=x&srsltid=y"
        )
        right = canonicalize_result_url("https://example.com/tool?id=7")
        different_business_value = canonicalize_result_url("https://example.com/tool?id=8")
        self.assertEqual(left, right)
        self.assertNotEqual(left, different_business_value)

    def test_query_context_is_frozen_into_a_nonmergeable_key(self):
        keyword = "context tool"
        us = evaluate_observation(
            observation(keyword, 20, [page(1, [], exhausted=True)])
        )
        gb_observation = observation(keyword, 20, [page(1, [], exhausted=True)])
        gb_observation["query_context"] = dict(
            gb_observation["query_context"], gl="gb"
        )
        gb_observation["pages"][0]["page_url"] = gb_observation["pages"][0][
            "page_url"
        ].replace("gl=us", "gl=gb")
        gb = evaluate_observation(gb_observation)
        self.assertNotEqual(
            us["TitleSupplyQueryContextKey"], gb["TitleSupplyQueryContextKey"]
        )

    def test_nonfrozen_search_parameter_is_rejected(self):
        payload = observation("context tool", 20, [page(1, [], exhausted=True)])
        payload["query_context"] = dict(payload["query_context"], pws=1)
        with self.assertRaisesRegex(ValueError, "query_context.pws"):
            evaluate_observation(payload)

    def test_wrong_boolean_types_are_rejected(self):
        keyword = "schema tool"
        malformed = page(1, [organic(keyword, "a")], exhausted=True, keyword=keyword)
        malformed["results"][0]["organic"] = "true"
        with self.assertRaisesRegex(ValueError, "organic must be boolean"):
            evaluate_observation(observation(keyword, 20, [malformed]))

        malformed = page(1, [], exhausted=True, keyword=keyword)
        malformed["blocked"] = "true"
        with self.assertRaisesRegex(ValueError, "blocked must be boolean"):
            evaluate_observation(observation(keyword, 20, [malformed]))

    def test_page_url_query_context_and_sequence_are_bound(self):
        keyword = "context tool"
        terminal = page(1, [organic(keyword, "a")], exhausted=True, keyword=keyword)
        terminal["page_url"] = terminal["page_url"].replace("start=0", "start=10")
        terminal["_autogenerated_page_url"] = False
        with self.assertRaisesRegex(ValueError, "start=10"):
            evaluate_observation(observation(keyword, 20, [terminal]))

        terminal = page(1, [organic(keyword, "a")], exhausted=True, keyword=keyword)
        terminal["page_url"] = terminal["page_url"].replace("gl=us", "gl=gb")
        terminal["_autogenerated_page_url"] = False
        with self.assertRaisesRegex(ValueError, "does not match query context"):
            evaluate_observation(observation(keyword, 20, [terminal]))

        terminal = page(1, [organic(keyword, "a")], exhausted=True, keyword=keyword)
        terminal["page_url"] += "&tbm=isch"
        terminal["_autogenerated_page_url"] = False
        with self.assertRaisesRegex(ValueError, "unsupported search parameter"):
            evaluate_observation(observation(keyword, 20, [terminal]))

    def test_volume_above_250_is_rejected(self):
        keyword = "scale tool"
        terminal = page(1, [], exhausted=True, keyword=keyword)
        with self.assertRaisesRegex(ValueError, "1..250"):
            evaluate_observation(observation(keyword, 300, [terminal]))

    def test_exhaustion_yields_exact_ratio_after_cross_page_url_deduplication(self):
        keyword = "small exact tool"
        repeated = organic(keyword, "a")
        repeated_on_page_two = dict(repeated, canonical_url="https://EXAMPLE.com/a/#again")
        result = evaluate_observation(
            observation(
                keyword,
                20,
                [
                    page(1, [repeated, organic(keyword, "b")]),
                    page(2, [repeated_on_page_two, organic(keyword, "c")], exhausted=True),
                ],
            )
        )
        self.assertEqual(result["TitleSupplyCountStatus"], "exact_exhausted")
        self.assertEqual(result["StrictTitleSupplyUniqueUrlCount"], 3)
        self.assertEqual(result["StrictTitleSupplyRatio"], 0.15)
        self.assertEqual(result["StrictTitleSupplyRoutingBand"], "provisional_strong")

    def test_nonorganic_results_are_not_counted(self):
        keyword = "boundary tool"
        result = evaluate_observation(
            observation(
                keyword,
                10,
                [
                    page(
                        1,
                        [
                            organic(keyword, "one"),
                            organic(keyword, "two"),
                            organic(keyword, "three"),
                            organic(keyword, "ad", organic=False),
                        ],
                        exhausted=True,
                    )
                ],
            )
        )
        self.assertEqual(result["StrictTitleSupplyUniqueUrlCount"], 3)
        self.assertEqual(result["StrictTitleSupplyRatio"], 0.3)
        self.assertEqual(result["StrictTitleSupplyRoutingBand"], "provisional_borderline")

    def test_organic_flag_alone_does_not_count_nonorganic_result_type(self):
        keyword = "typed result tool"
        module = organic(keyword, "module", result_type="people_also_ask")
        result = evaluate_observation(
            observation(keyword, 20, [page(1, [module], exhausted=True)])
        )
        self.assertEqual(result["TitleSupplyCountStatus"], "exact_exhausted")
        self.assertEqual(result["StrictTitleSupplyUniqueUrlCount"], 0)
        self.assertEqual(result["StrictTitleSupplyRatio"], 0.0)

    def test_plain_organic_title_mismatch_holds_query_integrity(self):
        keyword = "complete phrase tool"
        mismatch = organic(keyword, "mismatch", title="Complete phrase calculator")
        result = evaluate_observation(
            observation(keyword, 100, [page(1, [mismatch], exhausted=True)])
        )
        self.assertEqual(result["TitleSupplyQueryIntegrity"], "hold")
        self.assertEqual(result["StrictTitleSupplyUniqueUrlCount"], 1)
        self.assertEqual(result["TitleSupplyCountStatus"], "query_integrity_hold")
        self.assertFalse(result["TitleSupplyExhausted"])
        self.assertIsNone(result["StrictTitleSupplyRatio"])
        self.assertEqual(
            result["StrictTitleSupplyRoutingBand"],
            "not_assessable_query_integrity",
        )

    def test_threshold_is_floor_point_thirty_volume_plus_one(self):
        keyword = "crowded tool"
        results = [organic(keyword, str(index)) for index in range(4)]
        result = evaluate_observation(observation(keyword, 10, [page(1, results)]))
        self.assertEqual(result["TitleSupplyEarlyStopT"], 4)
        self.assertEqual(result["TitleSupplyCountStatus"], "lower_bound_gt_0_30")
        self.assertIsNone(result["StrictTitleSupplyRatio"])
        self.assertEqual(result["StrictTitleSupplyRoutingBand"], "provisional_high")

    def test_captcha_stops_before_results_on_that_page_are_counted(self):
        keyword = "captcha tool"
        result = evaluate_observation(
            observation(
                keyword,
                100,
                [
                    page(1, [organic(keyword, "a")]),
                    page(2, [organic(keyword, "b")], captcha=True),
                ],
            )
        )
        self.assertEqual(result["TitleSupplyCountStatus"], "blocked_captcha")
        self.assertEqual(result["StrictTitleSupplyUniqueUrlCount"], 1)
        self.assertTrue(result["TitleSupplyCaptcha"])
        self.assertEqual(result["StrictTitleSupplyRoutingBand"], "not_assessable_blocked")

    def test_repeated_page_is_blocked_not_exhausted(self):
        keyword = "loop tool"
        first = page(1, [organic(keyword, "a")], keyword=keyword)
        repeated = page(2, [], exhausted=True, page_url=first["page_url"])
        with self.assertRaisesRegex(ValueError, "start=0"):
            evaluate_observation(observation(keyword, 100, [first, repeated]))

    def test_different_page_urls_with_identical_results_are_blocked(self):
        keyword = "loop tool"
        first = page(1, [organic(keyword, "a"), organic(keyword, "b")])
        repeated_results = page(
            2,
            [organic(keyword, "a"), organic(keyword, "b")],
            exhausted=True,
        )
        result = evaluate_observation(
            observation(keyword, 100, [first, repeated_results])
        )
        self.assertEqual(result["TitleSupplyCountStatus"], "blocked_same_results_loop")
        self.assertFalse(result["TitleSupplyExhausted"])

    def test_exhausted_flag_without_terminal_evidence_is_not_exact(self):
        keyword = "terminal evidence tool"
        terminal = page(1, [organic(keyword, "a")], exhausted=True)
        terminal.pop("end_of_results_evidence")
        result = evaluate_observation(observation(keyword, 100, [terminal]))
        self.assertEqual(
            result["TitleSupplyCountStatus"],
            "not_assessable_terminal_evidence",
        )
        self.assertIsNone(result["StrictTitleSupplyRatio"])
        self.assertFalse(result["TitleSupplyExhausted"])

    def test_explicit_no_results_cannot_coexist_with_organic_results(self):
        keyword = "terminal evidence tool"
        terminal = page(1, [organic(keyword, "a")], exhausted=True)
        terminal["end_of_results_evidence"] = "explicit_no_results"
        result = evaluate_observation(observation(keyword, 100, [terminal]))
        self.assertEqual(
            result["TitleSupplyCountStatus"],
            "not_assessable_terminal_evidence",
        )
        self.assertIsNone(result["StrictTitleSupplyRatio"])

    def test_short_terminal_page_requires_a_real_page_size_bound(self):
        keyword = "terminal evidence tool"
        terminal = page(1, [organic(keyword, "a")], exhausted=True)
        terminal["end_of_results_evidence"] = "terminal_page_short_and_no_next"
        terminal["expected_page_size"] = 1
        held = evaluate_observation(observation(keyword, 100, [terminal]))
        self.assertEqual(
            held["TitleSupplyCountStatus"],
            "not_assessable_terminal_evidence",
        )
        terminal["expected_page_size"] = 10
        exact = evaluate_observation(observation(keyword, 100, [terminal]))
        self.assertEqual(exact["TitleSupplyCountStatus"], "exact_exhausted")
        terminal["expected_page_size"] = 11
        held_mismatch = evaluate_observation(observation(keyword, 100, [terminal]))
        self.assertEqual(
            held_mismatch["TitleSupplyCountStatus"],
            "not_assessable_terminal_evidence",
        )

    def test_full_page_duplicate_urls_are_not_short_terminal_evidence(self):
        keyword = "duplicate cards tool"
        results = [organic(keyword, "same") for _ in range(10)]
        terminal = page(1, results, exhausted=True, keyword=keyword)
        terminal["end_of_results_evidence"] = "terminal_page_short_and_no_next"
        terminal["expected_page_size"] = 10
        held = evaluate_observation(observation(keyword, 100, [terminal]))
        self.assertEqual(held["StrictTitleSupplyUniqueUrlCount"], 1)
        self.assertEqual(
            held["TitleSupplyCountStatus"],
            "not_assessable_terminal_evidence",
        )
        self.assertFalse(held["TitleSupplyExhausted"])

    def test_nine_duplicate_url_cards_can_be_short_but_numerator_stays_one(self):
        keyword = "duplicate cards tool"
        results = [organic(keyword, "same") for _ in range(9)]
        terminal = page(1, results, exhausted=True, keyword=keyword)
        terminal["end_of_results_evidence"] = "terminal_page_short_and_no_next"
        terminal["expected_page_size"] = 10
        exact = evaluate_observation(observation(keyword, 100, [terminal]))
        self.assertEqual(exact["TitleSupplyCountStatus"], "exact_exhausted")
        self.assertEqual(exact["StrictTitleSupplyUniqueUrlCount"], 1)
        self.assertEqual(exact["StrictTitleSupplyRatio"], 0.01)

    def test_result_type_schema_errors_fail_closed(self):
        keyword = "schema tool"
        malformed = organic(keyword, "a", result_type=1)
        terminal = page(1, [malformed], exhausted=True, keyword=keyword)
        with self.assertRaisesRegex(ValueError, "result_type must be string"):
            evaluate_observation(observation(keyword, 20, [terminal]))

    def test_ellipsis_auto_marks_title_as_truncated(self):
        keyword = "complete phrase tool"
        truncated = organic(keyword, "truncated", title="Complete phrase tool…")
        result = evaluate_observation(
            observation(keyword, 100, [page(1, [truncated], exhausted=True)])
        )
        self.assertEqual(result["TitleSupplyQueryIntegrity"], "hold")
        self.assertEqual(result["TitleSupplyCountStatus"], "query_integrity_hold")
        self.assertIsNone(result["StrictTitleSupplyRatio"])

    def test_midline_unicode_ellipsis_auto_marks_title_as_truncated(self):
        keyword = "complete phrase tool"
        truncated = organic(keyword, "truncated", title="Complete phrase tool ⋯")
        result = evaluate_observation(
            observation(keyword, 100, [page(1, [truncated], exhausted=True)])
        )
        self.assertEqual(result["TitleSupplyQueryIntegrity"], "hold")
        self.assertEqual(result["TitleSupplyCountStatus"], "query_integrity_hold")

    def test_nfkc_fullwidth_dot_sequence_marks_title_as_truncated(self):
        keyword = "complete phrase tool"
        truncated = organic(keyword, "truncated", title="Complete phrase tool ．．．")
        result = evaluate_observation(
            observation(keyword, 100, [page(1, [truncated], exhausted=True)])
        )
        self.assertEqual(result["TitleSupplyQueryIntegrity"], "hold")
        self.assertEqual(result["TitleSupplyCountStatus"], "query_integrity_hold")

    def test_truncated_title_mismatch_holds_query_integrity(self):
        keyword = "complete phrase tool"
        truncated = organic(
            keyword,
            "unknown",
            title="Complete phrase tool…",
            title_truncated=True,
        )
        result = evaluate_observation(
            observation(keyword, 100, [page(1, [truncated], exhausted=True)])
        )
        self.assertEqual(result["TitleSupplyQueryIntegrity"], "hold")
        self.assertEqual(result["StrictTitleSupplyUniqueUrlCount"], 1)
        self.assertEqual(result["TitleSupplyCountStatus"], "query_integrity_hold")
        self.assertFalse(result["TitleSupplyExhausted"])
        self.assertIsNone(result["StrictTitleSupplyRatio"])
        self.assertEqual(
            result["StrictTitleSupplyRoutingBand"],
            "not_assessable_query_integrity",
        )

    def test_unknown_title_counts_url_then_holds_integrity(self):
        keyword = "complete phrase tool"
        unknown = organic(keyword, "unknown", displayed_title=None)
        result = evaluate_observation(
            observation(keyword, 100, [page(1, [unknown], exhausted=True)])
        )
        self.assertEqual(result["StrictTitleSupplyUniqueUrlCount"], 1)
        self.assertEqual(result["TitleSupplyIntegrityIssueCount"], 1)
        self.assertEqual(result["TitleSupplyQueryIntegrity"], "hold")
        self.assertEqual(result["TitleSupplyCountStatus"], "query_integrity_hold")
        self.assertIsNone(result["StrictTitleSupplyRatio"])

    def test_punctuation_only_title_is_integrity_hold_not_parser_failure(self):
        keyword = "complete phrase tool"
        unknown = organic(keyword, "punctuation", title="—— …")
        result = evaluate_observation(
            observation(keyword, 100, [page(1, [unknown], exhausted=True)])
        )
        self.assertEqual(result["StrictTitleSupplyUniqueUrlCount"], 1)
        self.assertEqual(result["TitleSupplyQueryIntegrity"], "hold")
        self.assertIsNone(result["StrictTitleSupplyRatio"])

    def test_classic_allintitle_observation_is_legacy_only(self):
        keyword = "legacy tool"
        result = evaluate_observation(
            observation(
                keyword,
                50,
                [page(1, [organic(keyword, "a")], exhausted=True)],
                query="allintitle:legacy tool",
            )
        )
        self.assertEqual(result["TitleSupplyCountStatus"], "legacy_reference_only")
        self.assertIsNone(result["StrictTitleSupplyRatio"])
        self.assertEqual(
            result["StrictTitleSupplyRoutingBand"], "not_assessable_method_mismatch"
        )
        self.assertEqual(result["TitleSupplyQuery"], "allintitle:legacy tool")

    def test_single_reported_total_is_legacy_only(self):
        result = evaluate_observation(
            observation(
                "reported total tool",
                50,
                [],
                count_method="single_reported_result_count",
                reported_count=2,
            )
        )
        self.assertEqual(result["TitleSupplyCountStatus"], "legacy_reference_only")
        self.assertIsNone(result["StrictTitleSupplyRatio"])


if __name__ == "__main__":
    unittest.main()
